### ISSUE TITLE
Discrepancy in input description and example.

### ISSUE THREAD

**Issue by bahaa-desoky** [analyzere/problem_readme#1]
Hello. For the description of the input, it says that there are `n` lines between `0.0` and `10,000,000.0` inclusive. However, the example given uses the number `25,000,000.0` which is larger than `10,000,000.0`. I am not sure if this is a typo and if the intended range was `0.0`, `1,000,000,000.0`, like the range for limit and threshold.

**Comment by ajsteadly** [comment]
Thanks @bahaa-desoky! Fixed in https://github.com/analyzere/problem_readme/pull/2.
